### ISSUE TITLE
Segfault on XXhash.xxh64(nil)

### ISSUE THREAD

**Issue by mferrier** [nashby/xxhash#13]
Noticed I got a segfault on my local vagrant so I tested on an AWS instance and got the same. Doesn't happen on my mac.

[xxhash-segfault.txt](https://github.com/nashby/xxhash/files/364993/xxhash-segfault.txt)

Also happens on AWS instances.

**Comment by justinwsmith** [comment]
Thanks for the report.

I'm a little confused by the information in the segfault file. 
* Under "Control frame information" it indicates the call was to "xxh64" (xxhash.rb:10)
* However, under "C level backtrace information" it indicates the line xxhash.c:48 -- but that line is inside the function "xxhash32_streaming_hash_update" which should be unrelated to the above (and that stack frame is immediately below a frame in libpthread?)

Are you running multiple threads?  Are these threads possibly sharing a single XXhash object?  

If so, I don't think these XXhash objects are thread safe -- either each thread should have its own XXhash object, or there needs to be a mutex lock around each update on the hash,

**Comment by mferrier** [comment]
No multiple threads, just running it right on the command line (see the first line of the attachment).

Here's a segfault from another machine, but it also traces back to xxhash.c:48 in the C backtrace.

[segfault2.txt](https://github.com/nashby/xxhash/files/366135/segfault2.txt)

Is that C backtrace perhaps inaccurate? Is there something else I can look at?

**Comment by mferrier** [comment]
Oh actually, on these instances xxhash.c:48 is in `xxhash_xxh64`. Attached is the file at /data/homedirs/deploy/.gem/ruby/2.1.0/gems/xxhash-0.3.0/ext/xxhash/xxhash.c


[xxhash.c.txt](https://github.com/nashby/xxhash/files/366158/xxhash.c.txt)

**Comment by justinwsmith** [comment]
Oh!!  You're passing nil to the function and getting a segfault. (It's obvious now -- sorry, I didn't see this sooner.) 

Yes, this can be fixed. I'll try to write a patch to fix it by tonight. Thanks for catching this!

**Comment by nashby** [comment]
Nice catch. Thank you!
