### ISSUE TITLE
Release the GVL

### ISSUE THREAD

**Issue by thedrow** [nashby/xxhash#15]
It'd be useful to release the GVL while hashing to allow parallelism when using threaded applications.
It takes a bit of refactoring to get it done in Ruby though.
What do you think? Is it worthwhile doing?

**Comment by nashby** [comment]
@thedrow sorry but what's GVL? Or you mean GIL?

**Comment by thedrow** [comment]
In Ruby the GIL is called the *G*lobal *V*M *L*ock.

**Comment by nashby** [comment]
@thedrow oh, I see. If it's something you need in your app and it won't break anything for existing users I think it's worthwhile doing.

**Comment by nashby** [comment]
I'll close it for now. @thedrow feel free to ping me if you need anything!
