### ISSUE TITLE
Ruby warning: 'undefining the allocator of T_DATA class XXhash::XXhashInternal::StreamingHash64'

### ISSUE THREAD

**Issue by alistairjevans** [nashby/xxhash#25]
Warning seen when using the Digest class in this package.

```
/usr/local/bundle/gems/xxhash-0.5.0/lib/xxhash.rb:63: warning: undefining the allocator of T_DATA class XXhash::XXhashInternal::StreamingHash64
```

Probably a new thing on the later versions of ruby (3.3.6).  I'm on v0.5.0 of this package.

**Comment by alistairjevans** [comment]
From what I've seen elsewhere:

> Since Ruby 3.2 a new warning is printed when a Ruby class created in a C extension does not specify an allocate function or undefine it.

**Comment by nashby** [comment]
@alistairjevans I believe this is fixed by https://github.com/nashby/xxhash/commit/ef628ce9f82dcd50e11240156e32856bdb1c0eee. I'll try to release a new version next week!
