### ISSUE TITLE
File copy with xxhash Checksum

### ISSUE THREAD

**Issue by tilllt** [nashby/xxhash#9]
I'd like to create a ruby program that copies files as quickly as possible, while creating a xxhash checksum. 

Here is an example of doing this with md5 hashes:
http://stackoverflow.com/questions/31257577/creating-md5-checksum-while-copying-file-in-ruby

```
def copy_md5(source, target)
  chunk_size=1024
  md5 = Digest::MD5.new
  open(target,'w') do |t|
    open(source) do |s|
      while chunk=s.read(chunk_size)
        md5.update chunk
        t.write chunk
      end
    end
  end
  md5
end
```

but since the xxHash gem is missing an update function, i am not sure how this would be realized... or is the update function simply not mentioned in the documentation but exists?

**Comment by tilllt** [comment]
Justin, thanks so much for looking into my question. Still i cannot quite figure out how the above md5 example would translate to using xxHash instead...  would i still use the streaming function (i assume yes) like this? XXhash.xxh32_stream (chunk) ?

**Comment by justinwsmith** [comment]
It would work as nearly a drop-in replacement - you just instantiate a
class located in a different module. See the test code I wrote for an idea
of how it can be used.

Your question makes me realize that the class I wrote should probably be
placed in the Digest module. I'll take a closer look.

Justin

**Comment by justinwsmith** [comment]
With my latest code change, it should be as easy as replacing "Digest::MD5" with "Digest::XXHash32" or "Digest::XXHash64".

**Comment by tilllt** [comment]
Thanks again for making this work like the md5 digest. i keep getting this error though:

/home/xyz/.gem/ruby/gems/ruby-xxHash-0.4.0/lib/ruby-xxhash.rb:44:in `<module:Digest>': uninitialized constant Digest::Class (NameError)
	from /home/xyz/.gem/ruby/gems/ruby-xxHash-0.4.0/lib/ruby-xxhash.rb:43:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
	from dith_cp.old.rb:1:in `<main>'

when using the md5 example above and just replacing md5 with XXHash32... am i doing something wrong or do i have to update the Digest gem as well ... or is it important in which order i load / require the gems?

**Comment by justinwsmith** [comment]
I think that error is from my pure Ruby implementation of xxhash, which is
a separate project. Look for my ruby-xxhash repository and you can post the
issue there.

Justin

**Comment by justinwsmith** [comment]
I may have fixed the error that you reported here.  If you have any more problems with that gem, you can report them here: https://github.com/justinwsmith/ruby-xxhash

**Comment by nashby** [comment]
Thanks guys! Closing this.
